// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Network/P2P/Header/PacketChecksumType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tuckfirtle.Core.Network.P2P.Header {

  /// <summary>Holder for reflection information generated from Network/P2P/Header/PacketChecksumType.proto</summary>
  public static partial class PacketChecksumTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Network/P2P/Header/PacketChecksumType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketChecksumTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitOZXR3b3JrL1AyUC9IZWFkZXIvUGFja2V0Q2hlY2tzdW1UeXBlLnByb3Rv",
            "KtMBChJQYWNrZXRDaGVja3N1bVR5cGUSHQoZUEFDS0VUX0NIRUNLU1VNX1RZ",
            "UEVfTk9ORRAAEhwKGFBBQ0tFVF9DSEVDS1NVTV9UWVBFX01ENRABEh0KGVBB",
            "Q0tFVF9DSEVDS1NVTV9UWVBFX1NIQTEQAhIfChtQQUNLRVRfQ0hFQ0tTVU1f",
            "VFlQRV9TSEEyNTYQAxIfChtQQUNLRVRfQ0hFQ0tTVU1fVFlQRV9TSEEzODQQ",
            "BBIfChtQQUNLRVRfQ0hFQ0tTVU1fVFlQRV9TSEE1MTIQBUIlqgIiVHVja2Zp",
            "cnRsZS5Db3JlLk5ldHdvcmsuUDJQLkhlYWRlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tuckfirtle.Core.Network.P2P.Header.PacketChecksumType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketChecksumType {
    [pbr::OriginalName("PACKET_CHECKSUM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PACKET_CHECKSUM_TYPE_MD5")] Md5 = 1,
    [pbr::OriginalName("PACKET_CHECKSUM_TYPE_SHA1")] Sha1 = 2,
    [pbr::OriginalName("PACKET_CHECKSUM_TYPE_SHA256")] Sha256 = 3,
    [pbr::OriginalName("PACKET_CHECKSUM_TYPE_SHA384")] Sha384 = 4,
    [pbr::OriginalName("PACKET_CHECKSUM_TYPE_SHA512")] Sha512 = 5,
  }

  #endregion

}

#endregion Designer generated code
