// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Network/P2P/Header/PacketType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tuckfirtle.Core.Network.P2P.Header {

  /// <summary>Holder for reflection information generated from Network/P2P/Header/PacketType.proto</summary>
  public static partial class PacketTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Network/P2P/Header/PacketType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNOZXR3b3JrL1AyUC9IZWFkZXIvUGFja2V0VHlwZS5wcm90bypWCgpQYWNr",
            "ZXRUeXBlEhcKE1BBQ0tFVF9UWVBFX1VOS05PV04QABIUChBQQUNLRVRfVFlQ",
            "RV9QSU5HEAESGQoVUEFDS0VUX1RZUEVfSEFORFNIQUtFEAJCJaoCIlR1Y2tm",
            "aXJ0bGUuQ29yZS5OZXR3b3JrLlAyUC5IZWFkZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tuckfirtle.Core.Network.P2P.Header.PacketType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketType {
    [pbr::OriginalName("PACKET_TYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("PACKET_TYPE_PING")] Ping = 1,
    [pbr::OriginalName("PACKET_TYPE_HANDSHAKE")] Handshake = 2,
  }

  #endregion

}

#endregion Designer generated code
