// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Network/P2P/Header/PacketEncryptionType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tuckfirtle.Core.Network.P2P.Header {

  /// <summary>Holder for reflection information generated from Network/P2P/Header/PacketEncryptionType.proto</summary>
  public static partial class PacketEncryptionTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Network/P2P/Header/PacketEncryptionType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketEncryptionTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1OZXR3b3JrL1AyUC9IZWFkZXIvUGFja2V0RW5jcnlwdGlvblR5cGUucHJv",
            "dG8qVwoUUGFja2V0RW5jcnlwdGlvblR5cGUSHwobUEFDS0VUX0VOQ1JZUFRJ",
            "T05fVFlQRV9OT05FEAASHgoaUEFDS0VUX0VOQ1JZUFRJT05fVFlQRV9BRVMQ",
            "AUIlqgIiVHVja2ZpcnRsZS5Db3JlLk5ldHdvcmsuUDJQLkhlYWRlcmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tuckfirtle.Core.Network.P2P.Header.PacketEncryptionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketEncryptionType {
    [pbr::OriginalName("PACKET_ENCRYPTION_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PACKET_ENCRYPTION_TYPE_AES")] Aes = 1,
  }

  #endregion

}

#endregion Designer generated code
