// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Network/P2P/Header/PacketCompressionType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tuckfirtle.Core.Network.P2P.Header {

  /// <summary>Holder for reflection information generated from Network/P2P/Header/PacketCompressionType.proto</summary>
  public static partial class PacketCompressionTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for Network/P2P/Header/PacketCompressionType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketCompressionTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5OZXR3b3JrL1AyUC9IZWFkZXIvUGFja2V0Q29tcHJlc3Npb25UeXBlLnBy",
            "b3RvKoABChVQYWNrZXRDb21wcmVzc2lvblR5cGUSIAocUEFDS0VUX0NPTVBS",
            "RVNTSU9OX1RZUEVfTk9ORRAAEiMKH1BBQ0tFVF9DT01QUkVTU0lPTl9UWVBF",
            "X0RFRkxBVEUQARIgChxQQUNLRVRfQ09NUFJFU1NJT05fVFlQRV9HWklQEAJC",
            "JaoCIlR1Y2tmaXJ0bGUuQ29yZS5OZXR3b3JrLlAyUC5IZWFkZXJiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tuckfirtle.Core.Network.P2P.Header.PacketCompressionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketCompressionType {
    [pbr::OriginalName("PACKET_COMPRESSION_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PACKET_COMPRESSION_TYPE_DEFLATE")] Deflate = 1,
    [pbr::OriginalName("PACKET_COMPRESSION_TYPE_GZIP")] Gzip = 2,
  }

  #endregion

}

#endregion Designer generated code
